name: Push-to-EC2 instance

# Trigger deployment only on push to main branch 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC_SSH_KEY }}
          SOURCE: "."
          REMOTE_HOST: 'ec2-13-233-120-5.ap-south-1.compute.amazonaws.com'
          REMOTE_USER: 'ec2-user'
          TARGET: '/home/ec2-user'

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
        host: 'ec2-13-233-120-5.ap-south-1.compute.amazonaws.com'
          username: 'ec2-user'
          key: ${{ secrets.EC_SSH_KEY }}
          script: |
            sudo yum -y update
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            sudo su
            cd /home
            ls
            cd ec2-user
            sudo mv * /var/www/html
            sudo systemctl restart httpd
            